{% set name = "indexed_gzip" %}
{% set version = "1.7.1" %}
{% set sha256 = "c7ec19470a8a44d4541e36f537ed59ced8abe4a61c79a151d5ad340f0b959f3f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - zlib
    - msinttypes  # [win]
    - cython >=0.24
  run:
    - python
    - zlib


test:
  source_files:
    - pyproject.toml
  requires:
    - pytest
    - numpy
    - nibabel
    - cython

about:
  home: https://github.com/pauldmccarthy/indexed_gzip
  license: Zlib
  license_file: LICENSE
  summary: Fast random access of gzip files in Python
  dev_url: https://github.com/pauldmccarthy/indexed_gzip

extra:
  recipe-maintainers:
    - pauldmccarthy
