{% set name = "indexed_gzip" %}
{% set version = "1.6.4" %}
{% set sha256 = "97ea7740bc062682922ce98664a0d042e5fbfc5b9c1e79dd1ca5784383dbf0d3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - zlib
    - msinttypes  # [win]
    - cython >=0.24
  run:
    - python
    - zlib


test:
  source_files:
    - setup.cfg
  requires:
    - pytest
    - numpy
    - nibabel
    - coverage
    - pytest-cov
    - cython

about:
  home: https://github.com/pauldmccarthy/indexed_gzip
  license: Zlib
  license_file: LICENSE
  summary: Fast random access of gzip files in Python
  dev_url: https://github.com/pauldmccarthy/indexed_gzip

extra:
  recipe-maintainers:
    - pauldmccarthy
