appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ukvMV4JpqyowbeRP+Pdb+eXfn0qT8KiIqwRjI2Cdxq1GcEQa/YgaYGt5bA6q1thyxZJu0tkuuilPQvQYvmlzaZmtaCSJjp03IHABInCU0K5M6OcBu2uXjGhzStpGhRtg6RyurXj4okXuL/cuhEOvNXtwCjwCfsCX09NCCbJZd3pUPHyuE3mbjtq90pNCDFU3auOZ/t3NIuGEvCjE9dIhD4LH4qlV8ildmWghzwRzinhr7JJYZeltMHbXbX0Fse4qaCmxaAx3aHfY+cVOXxkoa98KvCf143/4ZpnqTobjqLKr0op79F/RP9Jt+ZPZbrcSYLeqx4xF3NZPlA/Dopi0YCeJml+Tpa280cKn+tn2DSWodAN6Psl3ecqf3AmvB9xp8UTDKUGN3pbbqqg6XzubduU7x6JT8eZmeU4sWnsklOecqRSHcboqn9DviCj9jO4/oR5PcCllrFwNq8b9ncJcqQchvad1zCyz1+vsHulGHuIxdme/nida7MiuOG8CU5t49XTU3bH2v4K+Sj9IozuvrtDFAvnSwwru0ZuEvZ4yMoqEiPWTWejGEJNP3je8IANZtCxRxEZFUMoEuywA6RXIYE4Y2SeaWlZHa3S2vcs0V5drbSubpAUi7eW8jVbigf9hZBkKDBwcXKzK6oQyhhAsSKB824bFY+WLNF+++vtTao0=}
provider:
  win: azure
