travis:
  secure:
    BINSTAR_TOKEN: ofIeSlARjyveSFOfs7wbAHsoUvQQGi3S50OgUs8cQF8RYeAvMCm8DqP75Oiz73mq98TtW3IcgNlnsSXrWYbMj7OGgrVYUNFO7nmn0p+gIo4Jon1WCVSkQI4CRn6NhYhrvnr4x/iQbj5N42/JmPqyFqxJIpyw+S2HO6Sh1LgnUpYThcznJhuX4IZ6VjZj0trfSJ7OxJlRyE9dCKUv6X7ACuivAoM1gp+IB2ugHws7pNA3gOqvkbSXk1cY0wPr0xKxMvmJyxe3FcuYwIsb1mlYyqA3oALTrBzA9NXNWvNksphYQAktKyZK+1pFW+V47AnWgWPJ/Zyz0RwrbCKSruz2o/B1DNZX8TaF1rZKR3DHdpLYB1WkZD2d+UwaOe29G3kDsFz4472wdj5HoX2XPRHfT6ExLSRh1h8IqXmJ9utSI7arS3Ifnj1oeP5Oa86ejPxbH8qBrPygyteNm8K0wmo+L6npCI/OyGJRC+hkc+025nQJnzYSN8q5cuKM44MrcCuw30Be6wAsUpXGdxOR4cKXe5OJtybqSUWTrW3TzjhdS1uj4uu/jt0Co9oXYTLq2RjodYnZNAEbxWLMt+zxUpJ37OaRyKGB0WvKCUFGevAIM+CrsDW9SDKXYhuqzSh2yMa+s7F7qXH8AThEZh9GLQ6kfnPsSJQxFZYUqJdHdKRilLs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
